### ISSUE TITLE
Tower Defense Mini Game Ideas

### ISSUE THREAD

**Issue by adediu25** [quaternary-game/quaternary#15]
I am thinking that the best way to teach relevant topics with this mini game is to add a sort of population management strategy to the game. The goal won't be "kill everything", but instead the player should ensure that there will still be prey around for future waves.

We can include the topics of food chain and trophic cascades by varying prey numbers based on past waves. We could also have two (or more) classes of prey, where one is above the other in the food chain (but the predators are above both). Eliminating too much of the lower class means less of the higher class can be sustained in the ecosystem. We can also include the environment within the trophic cascade which could have varying effects. 

Mutation and evolution can also be included through changing prey traits across waves, especially based on which prey survives the wave (natural selection).

The game will still be played with classic tower defense mechanics, and prey and predator traits/adaptations is what will drive the actual interactions between prey and predators.

Please tear this apart or add to it as you wish. My only worry is that this may be becoming a little too much for just being a mini game, I just don't want to be taking away from the main game.

**Comment by IllustratedMan-code** [comment]
Since this minigame is on the back-burner for now, closing the issue. Feel free to reopen when necessary.
