### ISSUE TITLE
Art style/Perspective vs Top-down

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/quaternary#17]
I've just completed two art pieces for the main game. These should act as "enemies" in the game (we could throw them in the tower defense mini game too). Give me some thoughts on these! Do you like the style? I'm not a very experienced visual artist, so any feedback would be great. 

![ezgif-1-64d700638a](https://github.com/quaternary-game/quaternary/assets/60514384/ad102c51-70dc-4d11-91d9-9859e440de56)
![ezgif-4-c455f0e1b9](https://github.com/quaternary-game/quaternary/assets/60514384/de4f4360-9588-477f-9a61-7d43144d0300)

The thing we have to decide on is if we want a "perspective" top-down game, or just a regular top-down game. The advantage of the normal top-down game is that we can just rotate the sprite in the direction that the character is moving. In a "perspective" game, I would have to render at least 8 different versions of each sprite, but some things look significantly better in the perspective view. 

The bacteriophage is definitely best viewed in a "perspective" view, it does not look good top-down:
![image](https://github.com/quaternary-game/quaternary/assets/60514384/351c946d-5e61-4ce5-a48f-32f1c92b97c9)

**Comment by adediu25** [comment]
I think these look great David! I do like the style.

Regular top-down would probably be more simple, although we would need to ensure the assets look good from that perspective. The choice is probably up to you as I assume this decision will mostly affect the art side of things.

**Comment by IllustratedMan-code** [comment]
I think I'm going to go mostly top-down, but a few assets (bacteriophage) will be perspective
