### ISSUE TITLE
Pause button disappears when in pause menu

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/quaternary#45]
**Describe the bug**
When pause menu is active, pause button disappears. 

**Expected behavior**
Pause button doesn't disappear. Unless this was intended the whole time?

https://github.com/quaternary-game/quaternary/assets/60514384/b8f9331e-c470-4948-8682-3b7039b0eb00

**Comment by IllustratedMan-code** [comment]
Also wanted to say that the functional pause menu is amazing. It feels almost like a real game lol

**Comment by adediu25** [comment]
intentional feature
