### ISSUE TITLE
Codon Player jitters

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/quaternary#46]
**Describe the bug**
Player trna jitters randomly sometimes

**To Reproduce**
1. play codon minigame
2. move mouse around randomly
3. observe

**Expected behavior**
No jitters

**Screenshots**
Unfortunately, snip and sketch does not pick up the jittering for some reason, no idea why (framerate too low?)

**Comment by ConnorMcKinney99** [comment]
I am unable to replicate any jitters with the minigame with the current build.
