### ISSUE TITLE
Codon cursor sticks around even after exiting

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/quaternary#47]
**Describe the bug**
After exiting the codon game, the cursor is still a DNA strand.

**To Reproduce**
 1. Play the codon game
 2. Exit the game
 3. Observe

**Expected behavior**
Cursor reverts back to normal. Maybe the custom cursor isn't necessary at all?

**Screenshots**

https://github.com/quaternary-game/quaternary/assets/60514384/eeb83f05-c305-4b83-b588-9a8d14fa4d52

**Comment by ConnorMcKinney99** [comment]
Removed custom cursor and asset.
