### ISSUE TITLE
Children don't inherit genotype if it changes in game

### ISSUE THREAD

**Issue by IllustratedMan-code** [quaternary-game/quaternary#85]
**Describe the bug**
After giving the organisms a bunch of traits and the asexual reproduction trait, the children do not inherit the genotype

**To Reproduce**
1. Add some traits to a character
2. add asexual reproduction
3.  watch and see

**Screenshots**
![image](https://github.com/quaternary-game/quaternary/assets/60514384/65f6a57f-8704-40b6-87b4-83c9b5da03ef)
Genotype of test character (after dragging and dropping)

![image](https://github.com/quaternary-game/quaternary/assets/60514384/b79786b1-a9ec-4855-bc4e-d1506970e163)
Genotype of child of test character 

![image](https://github.com/quaternary-game/quaternary/assets/60514384/66803192-c866-4171-9c01-8263bca6eb04)
Child and parent

**Comment by john-whiting** [comment]
![Fixed Genotype Passing](https://github.com/quaternary-game/quaternary/assets/25689099/8329e367-fbb1-4415-adc9-5320de0190ed)

Modified genotypes are now being cloned to the descendents of Asexual reproducers as of https://github.com/quaternary-game/quaternary/commit/2cf4056b2c088119370e64ed332b5e73fc9ba58e.

**Comment by IllustratedMan-code** [comment]
I think I know why the eyeballs don't show up, so I should be able to easily fix that

**Comment by IllustratedMan-code** [comment]
Fixed it with a direct commit to develop (sue me it was one line)
